### PR TITLE
Lock dependencies by major version only

### PR DESCRIPTION
**Pull request by MarshalX**
tests have been failed. because of not properly resolved union after upgrading:

> Updating pydantic (2.4.2 -> 2.5.2)

probably related to https://github.com/pydantic/pydantic-core/pull/ 867 (del ref)

**more details**

 we have these types:
```python
UnknownRecordTypePydantic = te.Annotated[
    t.Union[
        'models.AppBskyActorProfile.Main',
        'models.AppBskyFeedGenerator.Main',
        'models.AppBskyFeedLike.Main',
        'models.AppBskyFeedPost.Main',
        'models.AppBskyFeedRepost.Main',
        'models.AppBskyFeedThreadgate.Main',
        'models.AppBskyGraphBlock.Main',
        'models.AppBskyGraphFollow.Main',
        'models.AppBskyGraphList.Main',
        'models.AppBskyGraphListblock.Main',
        'models.AppBskyGraphListitem.Main',
    ],
    Field(discriminator='py_type'),
]
UnknownType: te.TypeAlias = t.Union[UnknownRecordTypePydantic, 'dot_dict.DotDictType']
```

the logic that was before upgrading: try to match type one from `UnknownRecordTypePydantic` using `py_type` field; if there is no match fallback to `DotDictType`

the logic after upgrading: it resolved all types as `DotDictType`

BUT when i delete `DotDictType` from the Union it resolves fine (ofc doesn't fallback to `DotDictType` but resolved the `UnknownRecordTypePydantic`)! 

```python
UnknownType: te.TypeAlias = t.Union[UnknownRecordTypePydantic]
```

all the models in `UnknownRecordTypePydantic` Unioin use this config:
```python
model_config = ConfigDict(extra='forbid', populate_by_name=True, strict=True)
```

so what should I do now to save `strict=True`, and exit from Union matching right after matching by discriminator (`py_type`) field? 

upd. `strict=False` doesn't help

### CODE REVIEW

**Comment by MarshalX** [comment]
after upgrading pydantic (2.4.2 -> 2.5.2) it starts mutating input data somehow. it should not affect real cases. tests load test data for each test now

**Comment by davidhewitt** [comment]
@MarshalX thanks for the ping on the smart union PR, is there a minimal repro you can share which exhibits the tagged union interaction? I'm very happy to take a look.

**Comment by MarshalX** [comment]
@davidhewitt happy to see you here! I tried to prepare a small script with reproducing but later found that unit tests work fine out of tests... That was something with the mutation of test data. Before 2.5 data wasn't mutated. Not the Union problem. Sorry for disturb. I didn't investigate the mutation and what causes it

**Comment by MarshalX** [comment]
@davidhewitt i created a corresponding issue about data mutation with reproducing. just wondering why the behaviour was changed https://github.com/pydantic/pydantic/issues/8349

**Pull request merged**
