### PR TITLE
Add get_bsky_post_by_url example

### PR DESCRIPTION
**Pull request by DGaffney**
Didn't have an example of this, needed one, so here ya go!

### CODE REVIEW

**Comment by MarshalX** [comment]
Hi! Thank you for your contribution. Pls check why linter fails. And let's rename file like get bsky posts by url. Since this url format is full about frontend implementation

**Comment by DGaffney** [comment]
> Hi! Thank you for your contribution. Pls check why linter fails. And let's rename file like get bsky posts by url. Since this url format is full about frontend implementation

sounds good! I'll rename after this linter run

**Comment by DGaffney** [comment]
@MarshalX can you resolve this one? Not sure what its complaining about at this point

**Comment by MarshalX** [comment]
@DGaffney I did not yet, but should be just a little work. Wanna to someday because traffic is huge

**Comment by DGaffney** [comment]
> @DGaffney I did not yet, but should be just a little work. Wanna to someday because traffic is huge
> 
> I want to reuse base websocket clients. Which will not parse frames, by just json. And speaking of the Jetstream models it uses own ones as I know. So just describe it with pydantic

Ok! When I can set aside some time the next few day's I'll get it in - Jaz is trying to push people over to jetstream so getting it in will help reduce load

**Comment by MarshalX** [comment]
@DGaffney  Awesome! Thank you! A few notes to keep in mind:
- both async and sync clients must be provided
- the public interface should be as much as simple and looks like the old one for real firehose (i want to have as smooth migration for ppl as possible)

**Comment by DGaffney** [comment]
> @DGaffney Awesome! Thank you! A few notes to keep in mind:
> 
> * both async and sync clients must be provided
> * use pydantic`s json serializer for speed
> * the public interface should be as much as simple and looks like the old one for real firehose (i want to have as smooth migration for ppl as possible)
> * simple random rolling between 4 official jetstreams instances by default

Sounds good! I'll at least get the ball rolling for you :)

**Pull request merged**
