### PR TITLE
Improve URL detection in auto_hyperlinks example

### LINKED ISSUE #141: Misdetection of URLs / links
The regexp in `extract_url_byte_positions` at https://github.com/MarshalX/atproto/blob/main/examples/advanced_usage/auto_hyperlinks.py does not appear to detect all valid URLs. Take for example:

```
https://www.cell.com/matter/fulltext/S2590-2385(23)00409-5?rss=yes
```

This is misdetected, and the URL is stopped before `(`

### PR DESCRIPTION
**Pull request by editor-syntax**
Fixes #141

### CODE REVIEW

**Comment by MarshalX** [comment]
Hi thank you! Could pls return blank empty line? Linter fails

**Comment by editor-syntax** [comment]
> Hi thank you! Could pls return blank empty line? Linter fails

Where do I return it?

**Comment by MarshalX** [comment]
> > Hi thank you! Could pls return blank empty line? Linter fails
> 
> 
> 
> Where do I return it?

Please check changes tab or GitHub actions logs. Line number 6. Between imports and function definition

**Comment by editor-syntax** [comment]
> > > Hi thank you! Could pls return blank empty line? Linter fails
> > 
> > 
> > Where do I return it?
> 
> Please check changes tab or GitHub actions logs. Line number 6. Between imports and function definition

Oh my bad. Done

**Comment by MarshalX** [comment]
@editor-syntax did i something wrong? just testing your regex with example from the issue

https://regex101.com/r/d3Hg78/1

image

**Comment by editor-syntax** [comment]
> @editor-syntax did i something wrong? just testing your regex with example from the issue
> 
> https://regex101.com/r/d3Hg78/1
> 
> image

Nope, but I did something wrong lol. It's updated now.
image

**Comment by MarshalX** [comment]
now it doesnt work for links without `(`/`)` :( 

image

**Comment by editor-syntax** [comment]
> now it doesnt work for links without `(`/`)` :(
> 
> image

Updated. That's my last resort lol!
image
image
image

**Comment by MarshalX** [comment]
@editor-syntax it looks working. But you deleted the usage of "aggressive" bool. Now we have only 1 regex. But you didn't delete the argument of the function. If we are gonna delete "aggressive" mode we should remove all related things to it: 

1. argument in the function
    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L8
2. tune docstring of the function
    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L10
3. remove flag from here:
    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L35
4. remove this because now will not have matches for links without protocol
    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L40

**Comment by editor-syntax** [comment]
> @editor-syntax it looks working. But you deleted the usage of "aggressive" bool. Now we have only 1 regex. But you didn't delete the argument of the function. If we are gonna delete "aggressive" mode we should remove all related things to it:
> 
> 1. argument in the function
>    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L8
> 2. tune docstring of the function
>    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L10
> 3. remove flag from here:
>    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L35
> 4. remove this because now we will not have matches for links without protocol
>    https://github.com/MarshalX/atproto/blob/5505bd14d02ee1dcf72b473348d6ab49e3ba52ee/examples/advanced_usage/auto_hyperlinks.py#L40

Yes, we can do that. I'll edit the example code and you edit the rest

**Review by MarshalX — APPROVED** [review]

**Comment by MarshalX** [comment]
thank you!

**Pull request merged**
