### PR TITLE
Add "delete_post" and "repost" methods

### PR DESCRIPTION
**Pull request by codybraun**
Hey not sure what branch to target here or if you want me to add a PR template or anything.

If it's useful to anybody else, a helper method to unshare a post was making my life easier so I went ahead and added one in my fork. I don't see that there's a place for to add much testing, but you can pretty easily verify this functionality with the included example if you swap in a real username/password.

Also added a very similar repost helper with example.

### CODE REVIEW

**Comment by MarshalX** [comment]
Hi! Of course, it could be added to the SDK! There are no tests yet 😅

**Comment by codybraun** [comment]
@MarshalX my bad, missed the linting check- should pass now I think. I also added a repost helper (with example) and pasted in some generic .gitignore (I ended up with tons of tracked pycache files for example just in the course of making this small client change)

**Comment by MarshalX** [comment]
ignore file is huge :( many things not related to the dev of atproto. pls don't force push iam refactoring you code a bit from my side

**Comment by MarshalX** [comment]
Thank you!

**Pull request merged**
