### PR TITLE
Fix grammar in the README

### LINKED ISSUE #483: would like to contribute a change to the readme
Current wording is: "The high-level methods are not cover the full need of developers."
Proposed change: "The high-level methods do not cover the full needs of developers."
Let me know, and I'll fork/submit a PR.

### PR DESCRIPTION
**Pull request by ErikPohl444**
Fixed some grammar in the readme.  Closes #483

### CODE REVIEW

**Review by MarshalX — COMMENTED** [review]
Thank you! Could you please review the entire README and fix the English? Also, I want to mention, we have 2 copies of the readme. One for GitHub and another one for the docs website. You should update this file as well: https://github.com/MarshalX/atproto/blob/main/docs/source/readme.content.md

**Comment by ErikPohl444** [comment]
Hello!  Glad to help.  I'll first align my current changes into:
https://github.com/MarshalX/atproto/blob/main/docs/source/readme.content.md

Then I'll read and revise as needed, submitting changes across both.

BTW: This is an excellent README overall, and one which got me started quickly.  The descriptive nature and word-choices are great.  I'd be honored to contribute little edits here and there when recommended.

Thank you.

**Comment by ErikPohl444** [comment]
Reviewed and synched changes between readmes.

**Comment by MarshalX** [comment]
@ErikPohl444 thank you! I synced changes between readmes in the single Pull Request. Pls check

**Review by MarshalX — APPROVED** [review]

**Comment by ErikPohl444** [comment]
All good.  Thank you!

**Pull request merged**
