### PR TITLE
Make codegen deterministic

### PR DESCRIPTION
**Pull request by DXsmiley**
I checked out the repo and, without changes, ran `atproto gen all` and unexpectedly ended up with a bunch of modified files. It looks like it's mostly just large chunks being moved around inside `atproto/xrpc_client/namespaces/sync_ns.py` though.

I *suspect* the culprit is `os.walk` but I'm not sure. Unfortunately I think it's a system-dependent thing so I don't quite have the ability to test this thoroughly on my machine.

This doesn't impact library users, but I would like to make a few other changes to the codegen without producing a completely unreadable diff.

### CODE REVIEW

**Comment by MarshalX** [comment]
What should we do to be sure?

**Comment by DXsmiley** [comment]
If you checkout my branch, run `atproto gen all` and something changes we'll know there's unfixed problems. If there's no changes then it's hard to say for _certain_ that everything's fixed but it'll give me a lot of confidence.

I think also adding a github action that runs the codegen and checks there's been no changes could also prevent non-determinism being reintroduced in the future. (and should also catch any instances of people making changes and then just forgetting to run the codegen script).

**Comment by MarshalX** [comment]
Could you implement this GitHub actions workflow in this PR please?

**Comment by DXsmiley** [comment]
@MarshalX done. I think it needs your manual approval before it'll actually run though.

**Comment by MarshalX** [comment]
Awesome! Could we run it in matrix on Linux macOS and Windows? To be sure that there is no difference between platforms

**Comment by DXsmiley** [comment]
done! needs another approval though

**Comment by DXsmiley** [comment]
made changes in accordance with https://github.com/snok/install-poetry#running-on-windows to try and get poetry working

**Comment by MarshalX** [comment]
problem of python 3.7. as ez fix (and end of life of python 3.7) let's use python 3.8 here? https://www.mail-archive.com/python-bugs-list@python.org/msg426517.html

**Comment by MarshalX** [comment]
thank you!

**Pull request merged**
